language: node_js
sudo: false
node_js:
  - 6 
env:
  - NODE_ENV="test"
before_script:
  - npm run db:setup:user
  - npm run db:reset
  - npm run db:seed
script:
  - npm test
  - npm run enforce
  - npm run lint
